name: deployment-pipeline

on: 
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs: 
  backend_pipeline:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: |
          cd backend
          npm install
      - run: |
          cd backend
          npm run lint
  frontend_pipeline:
    runs-on: ubuntu-22.04
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      NODE_ENV: 'test'
      SECRET: ${{ secrets.SECRET }}
      CONNECTIONSTRING: ${{ secrets.CONNECTIONSTRING }}
      PROFILEPICS_CONTAINER:  ${{ secrets.PROFILEPICS_CONTAINER }}
      RECIPEPICS_CONTAINER: ${{ secrets.RECIPEPICS_CONTAINER }}
      VITE_API_URL: http:localhost:3003/

    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Installing packets
        run: |
          cd frontend
          npm install
      - name: Linting
        run: |
          cd frontend
          npm run lint
      - name: Building
        run: |
          cd frontend
          npm run build
      - name: Testing wiht jest
        run: |
          cd frontend
          npm run test
          
      - name: Start server in the background
        run: |
          cd backend
          npm install
          bash ./build_step.sh
          npm run start &

      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: frontend
          command: npm run cy:run
  deployment_pipeline:
      needs: [backend_pipeline, frontend_pipeline]
      runs-on: ubuntu-22.04
      timeout-minutes: 5
      steps:
      -   uses: actions/checkout@v4
      -   uses: actions/setup-node@v4
          with:
            node-version: '20'
      - name: Trigger deployment
        env:
            COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        if: ${{ github.event_name == 'push' && !contains(join(env.COMMIT_MESSAGES), 'skip') }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
